name: multitrax_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  collection: ^1.19.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  formz: ^0.8.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  just_waveform: ^0.0.7
  path: ^1.9.1
  path_provider: ^2.1.5
  record: ^6.2.0
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.12.0
  uuid: ^4.5.3
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  bloc_lint: ^0.3.7
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.22
  flutter_test:
    sdk: flutter
  mockingjay: ^2.1.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  assets:
    - shorebird.yaml
  generate: true
  uses-material-design: true
